
###  Return - List of Users
GET http://localhost:3000/listUsers HTTP/1.1
content-type: application/json

### Returns - User By Id
GET http://localhost:3000/2 HTTP/1.1
content-type: application/json

### Add a User
post http://localhost:3000/add HTTP/1.1
content-type: application/json

{
    "name": "Jeremy A. West",
    "password": "cincocincocinco",
    "profession": "Software Engineer Extrordinair"
}

### Deletes - User By Id
### Reurns - New List of Users
DELETE  http://localhost:3000/3 HTTP/1.1
content-type: application/json

### Cancel changes
PUT http://localhost:3000/cancel HTTP/1.1
content-type: application/json

### Saves changes to File
PUT http://localhost:3000/save HTTP/1.1
content-type: application/json

###  Restore user file from backup
PUT http://localhost:3000/restore HTTP/1.1
content-type: application/json